DROP TABLE IF EXISTS PLATOS;
DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS RESTAURANTES;
DROP TABLE IF EXISTS PEDIDO_PLATO;
DROP TABLE IF EXISTS REST_PLATOS;

CREATE TABLE PLATOS (
    PLATO_ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR NOT NULL,
    PRECIO NUMERIC NOT NULL,
    FOTO VARCHAR NOT NULL,
    DESCRIPCION VARCHAR,
    SECCION INTEGER NOT NULL
);

CREATE TABLE PEDIDOS (
    PEDIDO_ID INTEGER IDENTITY PRIMARY KEY,
    MESA INTEGER NOT NULL,
    PRECIO NUMERIC NOT NULL,
    ESTADO INTEGER NOT NULL
);

CREATE TABLE RESTAURANTES (
    RESTAURANTE_ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR NOT NULL,
    DIRECCION VARCHAR NOT NULL
);

CREATE TABLE PEDIDO_PLATO (
    PEDIDO_ID INTEGER IDENTITY FOREIGN KEY,
    PLATO_ID INTEGER IDENTITY FOREIGN KEY,
    NUM_PLATOS INTEGER NOT NULL
);

CREATE TABLE REST_PLATOS (
    RESTAURANTE_ID INTEGER IDENTITY FOREIGN KEY,
    PLATO_ID INTEGER IDENTITY FOREIGN KEY
);